# -*- coding: utf-8 -*-
"""download

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PM5mI1nf9X99WumQtDFZE0tjNWiG1koh
"""

# src/download.py
### clear raw mtx files into h5ad and concatenate into one AnnData (ver 0.0)

import argparse, csv, shutil, glob, os
import scanpy as sc
import subprocess

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("--datasets", type=str, required=True)
  parser.add_argument("--outdir", type=str, required=True)
  args = parser.parse_args()

  ## read "datasets.txt", an external file
  with open("datasets.txt") as d:
    reader = csv.reader(d)
    datasets = [
            {"fname": row[0].strip(), "link": row[1].strip(), "label": row[2].strip()}
            for row in reader if row and not row[0].startswith("#")
    ]
  for ds in datasets:
    fname = ds["fname"]
    link = ds["link"]
    label = ds["label"]

    RAW_DIR = f"data/mtx/{fname}"
    OUT_DIR = os.path.join(args.outdir, fname)
    os.makedirs(RAW_DIR, exist_ok=True)
    os.makedirs(OUT_DIR, exist_ok=True)

    # download + unpack
    subprocess.run(["curl", "-L", link, "-o", f"{fname}.tar"], check=True)
    subprocess.run(["tar", "-xf", f"{fname}.tar", "-C", RAW_DIR], check=True)
    os.remove(f"{fname}.tar")

    # normalize + regroup
    files = glob.glob(os.path.join(RAW_DIR, "*"))
    for f in files:
      fname_only = os.path.basename(f)
      folder_name = fname_only.split(".")[0]
      sample_dir = os.path.join(OUT_DIR, folder_name)
      os.makedirs(sample_dir, exist_ok=True)

      if "matrix.mtx" in fname_only:
        dest = os.path.join(sample_dir, "matrix.mtx.gz")
      elif "barcodes.tsv.gz" in fname_only:
        dest = os.path.join(sample_dir, "barcodes.tsv.gz")
      elif "genes.tsv.gz" in fname_only or "features.tsv.gz" in fname_only:
        dest = os.path.join(sample_dir, "features.tsv.gz")
      else:
        dest = os.path.join(sample_dir, fname_only)

      shutil.move(f, dest)


    # build AnnData per dataset
    adatas = []
    for folder in sorted(glob.glob(os.path.join(OUT_DIR, "*"))):
        if os.path.isdir(folder):
            print(f"Reading {folder}")
            ad = sc.read_10x_mtx(folder, var_names="gene_symbols")
            ad.obs["sample"] = os.path.basename(folder)
            adatas.append(ad)

    if adatas:
        adata = adatas[0].concatenate(adatas[1:], join="outer", batch_key="sample_id")
        print(adata)
        adata.write(f"{OUT_DIR}/{label}_{fname}.h5ad")
    else:
        print("No samples found!")

if __name__ == "__main__":
    main()